Use GitHub OAuth role from GitHub
cisagov/cyhy_amis pull request #135
Opened 2018-10-26 14:57 UTC by jsf9k

Remove it from this repository.

2018-10-26 18:49 UTC, felddy approved these changes
I like these changes, and would be happy to see us adopt it across all of our projects. So dry!

2018-10-26 19:25 UTC, jsf9k commented
I'd still like @dav3r and @KyleEvers to weigh in before merging.  I too think that in most cases separate and reusable Ansible roles are the way forward, but I want others to voice concerns if they have them.

2018-10-29 14:35 UTC, KyleEvers commented
I also like these changes. Looks good.

2018-10-31 18:56 UTC, dav3r requested changes
I'm a big fan of this approach- let's keep it going. 👍

2018-10-31 18:56 UTC, dav3r commented on README.md
> +will update the roles that are being pull from external sources.  This
```suggestion
will update the roles that are being pulled from external sources.  This
```

2018-10-31 19:07 UTC, dav3r approved these changes

2018-10-31 19:10 UTC, merged