Cyhy dashboard
cisagov/cyhy_amis pull request #149
Opened 2018-12-07 18:00 UTC by KyleEvers

2018-12-07 20:01 UTC, dav3r commented
I gave some verbal comments to @KyleEvers and he is working on the changes.

2018-12-12 19:41 UTC, dav3r requested changes
Just needs a few minor changes @KyleEvers and then this should be good to go

2018-12-12 19:41 UTC, dav3r commented on ansible/roles/cyhy_dashboard/tasks/main.yml
> +#
These three comment lines can be removed or updated to more accurately reflect what is happening here

2018-12-12 19:41 UTC, dav3r commented on ansible/roles/cyhy_dashboard/tasks/main.yml
> +- name: Start ncat-webd
Nitpick: This should read: "Start ncat**s**-webd'"

2018-12-12 19:41 UTC, dav3r commented on packer/ansible/roles/cyhy_dashboard/tasks/main.yml
> +#
These 3 comment lines can be removed.

2018-12-12 19:41 UTC, dav3r commented on packer/ansible/roles/cyhy_dashboard/tasks/main.yml
> +- name: Install pip
We already have a `pip` role at `packer/ansible/roles/pip`.  This section should be removed and `pip` should be added to the list of dependencies in `packer/ansible/roles/cyhy_dashboard/meta/main.yml`

2018-12-13 15:44 UTC, jsf9k requested changes
The systemd unit stuff isn't necessary for approval, but if not it should be fixed in a future pull request.

Please see my other comments as well.

2018-12-13 15:44 UTC, jsf9k commented on ansible/roles/cyhy_dashboard/tasks/main.yml
> +    mode: 0750
Is there a reason why `/var/cyhy` and `/var/cyhy/web` need different modes?

2018-12-13 15:44 UTC, jsf9k commented on ansible/roles/cyhy_dashboard/tasks/main.yml
> +- name: Start ncats-webd
This isn't a good way to start a service.  If the instance reboots the service won't be restarted.  You should really create a systemd unit instead.

Look at the packer and terraform ansibles for the commander for an example.

2018-12-13 15:44 UTC, jsf9k commented on ansible/roles/cyhy_dashboard/tasks/main.yml
> +# Run `dev-build` target as root
This is nit-picky, but "Run" is incorrect here.  It should be "Build".

2018-12-13 15:44 UTC, jsf9k commented on ansible/roles/cyhy_dashboard/tasks/main.yml
> +- make:
Again, this is a terrible way to start a service.  If the instance reboots the service won't be restarted.  You should really create a systemd unit instead.

2018-12-13 15:44 UTC, jsf9k commented on packer/ansible/roles/cyhy_dashboard/README.md
> +     - hosts: cyhy_dashboard
Bad formatting here.  The lines that follow are not sufficiently indented.

2018-12-13 15:44 UTC, jsf9k commented on ansible/roles/cyhy_dashboard/meta/main.yml
> +  - github_oauth
I don't see where the token from `github_oauth` is used here.

2018-12-13 15:44 UTC, jsf9k commented on packer/ansible/roles/cyhy_dashboard/tasks/main.yml
> +- name: Create /var/cyhy/webui directory
The directory name is incorrect in this comment.

2018-12-13 15:44 UTC, jsf9k commented on terraform/cyhy_dashboard_ec2.tf
> +  instance_type = "${local.production_workspace ? "t3.medium" : "t3.medium"}"
No need for a conditional if the result is the same either way.

2018-12-13 21:42 UTC, dav3r approved these changes

2018-12-18 19:36 UTC, jsf9k approved these changes

2018-12-18 19:37 UTC, merged