Tear down Docker composition before bringing it up again
cisagov/cyhy_amis pull request #666
Opened 2023-07-31 13:51 UTC by jsf9k

## 🗣 Description ##

This pull request makes a change to tear down the [cisagov/orchestrator](https://github.com/cisagov/orchestrator) Docker composition before bringing it up again.

## 💭 Motivation and context ##

We have had an issue lately where the Docker composition does not start up correctly otherwise; this change will obviate said issue.

## 🧪 Testing ##

All automated tests pass.  I made this same change manually on the production system.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All new and existing tests pass.

2023-07-31 13:52 UTC, jsf9k commented
:imp:

2023-07-31 13:52 UTC, jsf9k commented
The GitHub Actions checks should pass once #661 is merged and this PR is rebased.

2023-07-31 13:58 UTC, dav3r approved these changes

2023-07-31 13:58 UTC, dav3r commented on ansible/roles/orchestrator/tasks/main.yml
> +        job: cd /var/cyhy/orchestrator && docker compose down && docker compose up --detach 2>&1 | /usr/bin/logger -t orchestrator
As long as we are expanding from short-form to long-form option names:
```suggestion
        job: cd /var/cyhy/orchestrator && docker compose down && docker compose up --detach 2>&1 | /usr/bin/logger --tag orchestrator
```

2023-08-22 14:48 UTC, jsf9k commented
@mcdonnnj - Is there a reason why #661 can't be merged now?

2023-08-23 17:29 UTC, dav3r approved these changes
⬇️ ⬆️ 👍

2023-08-24 15:37 UTC, mcdonnnj requested changes
This is a necessary evil right now but I would like an issue created to track hopefully unwinding this change once we sort out the underlying issue.

2023-08-24 17:07 UTC, jsf9k commented
> This is a necessary evil right now but I would like an issue created to track hopefully unwinding this change once we sort out the underlying issue.

Please see issue #668 and commit cd78009.

2023-08-24 18:11 UTC, mcdonnnj approved these changes

2023-08-24 20:40 UTC, merged